title = "neuralop"

[tool.black]
    line-length = 100
    include = ["neuralop/layers/*"]

[tool.setuptools_scm]

[tool.ruff]
line-length = 100
ignore = ["E501", "E741", "E731"]
extend-exclude = [
]

[tool.isort]
profile = "black"